"""Second

Revision ID: 18d6d1c7c250
Revises: 
Create Date: 2022-11-19 22:52:29.739651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d6d1c7c250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'rating', existing_type=sa.VARCHAR(length=10),
        type=sa.VARCHAR(length=30))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'rating', existing_type=sa.VARCHAR(length=10))
    # ### end Alembic commands ###
